import { TaskActionType } from '../planner/task.planner.js';

export interface ValidationResult {
  isValid: boolean;
  sanitizedContent: string;
  warnings: string[];
}

export class TaskValidator {
  public validate(action: TaskActionType, content: string): ValidationResult {
    const warnings: string[] = [];
    let isValid = true;
    let sanitizedContent = content.trim();

    if (!sanitizedContent || sanitizedContent.length === 0) {
      return {
        isValid: false,
        sanitizedContent: 'No content was generated by the AI model.',
        warnings: ['Empty LLM output received'],
      };
    }

    switch (action) {
      case 'GENERATE_ACCEPTANCE_CRITERIA':
        if (!sanitizedContent.includes('Given') && !sanitizedContent.includes('When')) {
          warnings.push('Acceptance criteria output does not follow Given/When/Then format strictly');
        }
        break;

      case 'ESTIMATE_COMPLEXITY':
        if (!sanitizedContent.includes('XS') && !sanitizedContent.includes('S') && !sanitizedContent.includes('M') && !sanitizedContent.includes('L') && !sanitizedContent.includes('XL')) {
          warnings.push('Estimator did not specify a standard T-shirt size');
        }
        break;

      case 'ANALYZE_RISKS':
        if (!sanitizedContent.toLowerCase().includes('risk')) {
          warnings.push('Risk analysis output missing explicit risk classification');
        }
        break;

      case 'GENERATE_SUBTASKS':
        if (!sanitizedContent.includes('-') && !sanitizedContent.includes('*') && !sanitizedContent.includes('1.')) {
          warnings.push('Subtasks output is not formatted as a markdown list');
        }
        break;
    }

    return {
      isValid,
      sanitizedContent,
      warnings,
    };
  }
}

export const taskValidator = new TaskValidator();
